sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t manickgm08/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true manickgm08/docker-react npm run test -- --coverage